name: babel
description: Babel is a CLI tool for translations management for Flutter apps.
version: 0.0.4-prerelease

homepage: https://github.com/nikosportolos/babel
repository: https://github.com/nikosportolos/babel
documentation: https://github.com/nikosportolos/babel
issue_tracker: https://github.com/nikosportolos/babel/issues

environment:
  sdk: '>=3.1.0 <4.0.0'

executables:
  babel:

dependencies:
  analyzer: ^6.8.0
  ansix: 0.3.3
  dart_cmder: ^0.0.5-prerelease
  args: ^2.4.2
  trace: ^0.0.6-prerelease
  collection: ^1.18.0
  data_class_plugin: ^1.1.0
  path: ^1.9.1
  yaml: ^3.1.2
  meta: ^1.16.0

dev_dependencies:
  lints: ^5.0.0
  mocktail: ^1.0.4
  tachyon: ^0.3.0
  test: 1.25.2

screenshots:
  - description: 'Babel: Translations management for Flutter apps'
    path: assets/images/banner.webp
  - description: 'This is an example usage of "babel list all -m grid"'
    path: assets/images/examples/list-all-grid.png
  - description: 'This is an example usage of "babel list all -m tree"'
    path: assets/images/examples/list-all-tree.png
  - description: 'This is an example usage of "babel list all -m json"'
    path: assets/images/examples/list-all-json.png

topics:
  - translations
  - localization
  - internationalization
  - management
  - cli
