name: babel
description: Babel is a CLI tool for translations management for Flutter apps.
version: 0.0.2-prerelease

homepage: https://github.com/nikosportolos/babel
repository: https://github.com/nikosportolos/babel
documentation: https://github.com/nikosportolos/babel
issue_tracker: https://github.com/nikosportolos/babel/issues

environment:
  sdk: '>=3.1.0 <4.0.0'

executables:
  babel:

dependencies:
  analyzer: ^6.2.0
  ansix: ^0.3.0
  dart_cmder: ^0.0.4-prerelease
  args: ^2.4.2
  trace: ^0.0.5-prerelease
  collection: ^1.18.0
  data_class_plugin: ^1.1.0
  path: ^1.8.3
  yaml: ^3.1.2

dev_dependencies:
  lints: ^2.1.1
  mocktail: ^1.0.1
  tachyon: ^0.1.0
  test: ^1.24.7

screenshots:
  - description: 'Babel: Translations management for Flutter apps'
    path: assets/images/banner.png
  - description: 'This is an example usage of "babel list all -m grid"'
    path: assets/images/examples/list-all-grid.png
  - description: 'This is an example usage of "babel list all -m tree"'
    path: assets/images/examples/list-all-tree.png
  - description: 'This is an example usage of "babel list all -m json"'
    path: assets/images/examples/list-all-json.png

topics:
  - translations
  - localization
  - internationalization
  - management
  - cli
