name: babel
description: Translations management for Flutter apps
version: 0.0.1-prerelease

homepage: https://github.com/nikosportolos/babel
repository: https://github.com/nikosportolos/babel
documentation: https://github.com/nikosportolos/babel
issue_tracker: https://github.com/nikosportolos/babel/issues

environment:
  sdk: '>=3.1.0 <4.0.0'

executables:
  babel:

dependencies:
#  analyzer: ^5.13.0
  analyzer: ^6.2.0
  analyzer_plugin: ^0.11.3
  ansix: ^0.2.0
  dart_cmder:
    path: D:/workspace/Flutter/Packages/dart_cmder
  trace: ^0.0.1-prerelease
  args: ^2.4.2
  collection: ^1.18.0
  data_class_plugin: ^1.0.4
  file: ">=6.0.0 <8.0.0"
  glob: ^2.1.2
  path: ^1.8.3
  yaml: ^3.1.2

dependency_overrides:
  analyzer: ^5.13.0

dev_dependencies:
  lints: ^2.1.1
  tachyon: ^0.0.9
